name: portfolio

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  deployment:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          npm i
          npm run build
      - name: Restart PM2
        run: |
          pm2 restart portfolio